---
- name: Check if tldr++ already exists
  stat:
    path: "/usr/local/bin/tldr"
  register: tldr_stat

- name: Download tldr++ from source
  get_url:
    dest: /home/{{ new_user }}/
    url: "https://github.com/isacikgoz/tldr/releases/download/v{{ tldr_version }}/{{ tldr_filename }}"
  when: not tldr_stat.stat.exists

- name: Unpack tldr++ archive
  become: yes
  unarchive:
    src: /home/{{ new_user }}/{{ tldr_filename }}
    dest: /usr/local/bin
    creates: /usr/local/bin/{{ tldr_filename }}
    mode: a+x
  when: not tldr_stat.stat.exists
