---
- name: Check if tldr++ already exists
  stat:
    path: "/usr/local/bin/tldr"
  register: tldr_stat

- name: Download tldr++ from source
  get_url:
    dest: "/home/{{ ansible_user_id }}/"
    url: "https://github.com/isacikgoz/tldr/releases/download/v{{ tldr_version }}/{{ tldr_filename }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  when: not tldr_stat.stat.exists

- name: Unpack tldr++ archive
  become: yes
  unarchive:
    src: "/home/{{ ansible_user_id }}/{{ tldr_filename }}"
    dest: "/usr/local/bin"
    creates: "/usr/local/bin/{{ tldr_filename }}"
    mode: a+x
  when: not tldr_stat.stat.exists

- name: Ensure downloaded file is removed
  file:
    path: "/home/{{ ansible_user_id }}/{{ tldr_filename }}"
    state: absent
