---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - zsh
    - tmux
    - ssh
    - git
    - nodejs
    - npm
    - ruby
    - ruby-dev
    - rubygems
    - cowsay
    - neofetch
  become: yes

- name: Set the shell to zsh
  user:
    name: sturm
    shell: /bin/zsh
  become: yes

- name: Check if oh-my-zsh already exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Install oh-my-zsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not stat_oh_my_zsh_result.stat.exists

- name: Install Powerlevel10k
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: Install lolcat and colorls
  gem:
    name: "{{ item }}"
    state: present
  with_items:
    - lolcat
    - colorls

- name: Get the dotfiles from the GitHub repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local }}"

- name: Ensure all configured dotfiles are links
  command: "ls -F {{ home }}/{{ item }}"
  register: existing_dotfile_info
  failed_when: false
  check_mode: false
  changed_when: false
  with_items: "{{ dotfiles_files }}"

- name: Remove existing dotfiles if a replacement is being linked
  file:
    path: "{{ home }}/{{ dotfiles_files[item.0] }}"
    state: absent
  when: "'@' not in item.1.stdout"
  with_indexed_items: "{{ existing_dotfile_info.results }}"

- name: Link dotfiles into home folder
  file:
    src: "{{ dotfiles_repo_local }}/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
  become: false
  with_items: "{{ dotfiles_files }}"
