---
# misc
github_access_token: "{{ vault_github_access_token }}"
new_user: "{{ ansible_user }}"
wsl_name: "{{ ansible_env.WSL_DISTRO_NAME is defined | ternary('@' + (ansible_env.WSL_DISTRO_NAME | lower), '') }}"
ssh_key_comment: "{{ ansible_user_id }}{{ wsl_name }}@{{ ansible_hostname | lower }}"
nvs_home: "/home/{{ new_user }}/.nvs"

# weareinteractive.users
users:
  - username: "{{ new_user }}"
    name: Chris McGee
    uid: 1000
    password: "{{ vault_user_password }}"
    authorized_keys:
      - "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    home_create: yes
    home_mode: "0750"
    groups:
      - admin
    append: yes

# geerlingguy.git

# viasite-ansible.zsh
zsh_antigen_bundles_extras:
  - joel-porquet/zsh-dircolors-solarized
  - romkatv/powerlevel10k
  - zsh-users/zsh-syntax-highlighting
  - zsh-users/zsh-completions
  - zsh-users/zsh-autosuggestions
  - colored-man-pages
  - npm
  - sudo
  - git
zsh_autosuggestions_bind_key: "^U"
zsh_antigen_theme: "romkatv/powerlevel10k powerlevel10k"

# geerlingguy.ruby
ruby_install_gems:
  - colorls
  - lolcat
ruby_install_gems_user: "{{ ansible_user_id }}"

# geerlingguy.dotfiles
dotfiles_repo: "https://github.com/SturmB/dotfiles.git"
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: "~/dotfiles"
dotfiles_files:
  - .aliases
  - .fzf.zsh
  - .gitconfig
  - .p10k.zsh
  - .tmux.conf
  - .zshrc.local

# tldr
tldr_version: "0.6.1"
tldr_filename: "tldr_{{ tldr_version }}_linux_amd64.tar.gz"
