---
# misc
github_access_token: 709f29af957aa7518635e5dbd378b2b19a6d3801
new_user: "{{ ansible_user }}"
ssh_key_comment: "{{ ansible_user_id }}@{{ ansible_hostname }}"
nvs_home: "~/.nvs"

# weareinteractive.users
users:
  - username: "{{ new_user }}"
    name: Chris McGee
    uid: 1000
    password: $6$f.IoSva2Rs3A28a3$MxegsR/w1wxPwAdELylSu/vuJSCML8LwDv.eaLl2DjkwuPfAb1VQLT7oWioV1xxVEVGTxyYPLHMBBVve7MsO9.
    authorized_keys:
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    home_create: yes
    home_mode: "0750"
    groups:
      - admin
    append: yes

# geerlingguy.git

# viasite-ansible.zsh
zsh_antigen_bundles_extras:
  - joel-porquet/zsh-dircolors-solarized
  - romkatv/powerlevel10k
  - zsh-users/zsh-syntax-highlighting
  - zsh-users/zsh-completions
  - zsh-users/zsh-autosuggestions
  - colored-man-pages
  - npm
  - sudo
  - git
zsh_autosuggestions_bind_key: "^U"
zsh_antigen_theme: "romkatv/powerlevel10k powerlevel10k"

# geerlingguy.ruby
ruby_install_gems:
  - colorls
  - lolcat
  - travis
ruby_install_gems_user: "{{ ansible_user_id }}"

# geerlingguy.dotfiles
dotfiles_repo: "https://github.com/SturmB/dotfiles.git"
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_files:
  - .aliases
  - .fzf.zsh
  - .gitconfig
  - .p10k.zsh
  - .tmux.conf
  - .zshrc.local

# tldr
tldr_version: "0.6.1"
tldr_filename: "tldr_{{ tldr_version }}_linux_amd64.tar.gz"
