---
- hosts: do
  remote_user: root
  gather_facts: false

  vars_files:
    - ../inventories/group_vars/all/vars.yml
    - ../inventories/group_vars/all/vault.yml

  pre_tasks:
    - name: Wait for port 22 to become available
      local_action: "ansible.builtin.wait_for port=22 host={{ inventory_hostname }}"
      tags:
        - tldr

    - name: Gathering Facts
      ansible.builtin.setup:

  tasks:
    - name: Ensure user is created
      ansible.builtin.include_role:
        name: weareinteractive.users

- hosts: all
#  remote_user: "{{ new_user }}"
  gather_facts: true
  # environment:
  #   NVS_HOME: "{{ nvs_home }}"

  vars_files:
    - ../inventories/group_vars/all/vars.yml
    - ../inventories/group_vars/all/vault.yml

  pre_tasks:
    - name: Adjust fact for Pengwin
      ansible.builtin.set_fact: ansible_os_family="Debian"
      when: ansible_os_family == "Pengwin"

    - name: Ensure apt packages are installed
      ansible.builtin.apt:
        state: latest
        update_cache: yes
        # upgrade: yes
        name:
          - cowsay
          - fortune
          - figlet
          - neofetch
          - bat
          - php-gd
          - php-zip
          - php7.4-gd
          - php7.4-zip
      become: yes

  tasks:
    - name: Ensure lsd is installed
      ansible.builtin.apt:
        deb: https://github.com/Peltoche/lsd/releases/download/0.20.1/lsd_0.20.1_amd64.deb
      become: yes

    - name: Ensure Ruby and gems are installed
      ansible.builtin.include_role:
        name: geerlingguy.ruby
        apply:
          become: yes

    - name: Ensure zsh and all plugins are installed
      ansible.builtin.include_role:
        name: viasite-ansible.zsh
        apply:
          become: yes

    - name: Ensure tldr++ is installed
      ansible.builtin.import_tasks: ../tasks/tldr.yml
      tags:
        - tldr
      become: yes

    - name: Ensure bat is installed
      ansible.builtin.import_tasks: ../tasks/bat.yml
      tags:
        - bat

    - name: Ensure SSH directory exists
      ansible.builtin.file:
        path: ~/.ssh
        state: directory

    - name: Ensure SSH key pair is created
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_ed25519
        state: present
        type: "ed25519"
        comment: "{{ ssh_key_comment }}"
      register: keys

    - name: Ensure SSH key is on GitHub
      community.general.github_key:
        name: "{{ ssh_key_comment }}"
        token: "{{ github_access_token }}"
        state: present
        pubkey: "{{ keys.public_key }}"

    - name: Ensure dotfiles repo is present and linked
      ansible.builtin.import_role:
        name: geerlingguy.dotfiles

    - name: Initialize tldr++
      ansible.builtin.command:
        cmd: tldr
        creates: ~/.local/share/tldr/
      tags:
        - tldr

    - name: Ensure tmux is installed properly
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm

    - name: See if NVS is already installed
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: export NVS_HOME="$HOME/.nvs"
        state: present
      check_mode: true
      register: zshrc
      tags:
        - nvs

    - name: Clone the NVS repo
      ansible.builtin.git:
        repo: https://github.com/jasongin/nvs
        dest: "{{ nvs_home }}"
        version: v1.6.0
      ignore_errors: true
      when: (zshrc is changed) or (zshrc is failed)
      tags:
        - nvs

    - name: Ensure NVS is installed
      ansible.builtin.shell: ". {{ nvs_home }}/nvs.sh install"
      when: (zshrc is changed) or (zshrc is failed)
      tags:
        - nvs
      debugger: on_failed
