---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Create new Droplet.
      digital_ocean_droplet:
        oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        state: present
        name: ansible-test
        private_networking: yes
        size: s-1vcpu-1gb
        image: ubuntu-18-04-x64
        region: nyc3
        ssh_keys: 24968128
        unique_name: yes
      register: do

    - name: Add new host to our inventory
      add_host:
        name: "{{ do.data.ip_address }}"
        groups: do
      when: do.data is defined
      changed_when: False
