---
# misc
github_access_token: 709f29af957aa7518635e5dbd378b2b19a6d3801
new_user: "sturm"

# weareinteractive.users
users:
  - username: "{{ new_user }}"
    name: Chris McGee
    uid: 1000
    password: $6$somesecretsalthe$xrTgcmmIHNkg9bIsyMm6fDq6W6sCH8.r4J8FWFxPirXFmN61xr6PP7kX.I3dBEEkUyDFoQIfk0mfKaWEgAstD1
    authorized_keys:
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    home_create: yes
    home_mode: "0750"
    groups:
      - admin
    append: yes

# geerlingguy.git

# viasite-ansible.zsh
zsh_user: "{{ new_user }}"
zsh_antigen_bundles_extras:
  - joel-porquet/zsh-dircolors-solarized
  - romkatv/powerlevel10k
  - zsh-users/zsh-syntax-highlighting
  - zsh-users/zsh-completions
  - zsh-users/zsh-autosuggestions
zsh_autosuggestions_bind_key: "^U"
zsh_antigen_theme: "romkatv/powerlevel10k powerlevel10k"

# geerlingguy.ruby
ruby_install_gems:
  - colorls
  - lolcat
ruby_install_gems_user: "{{ new_user }}"

# geerlingguy.dotfiles
dotfiles_repo: "https://github.com/SturmB/dotfiles.git"
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_files:
  - .aliases
  - .fzf.zsh
  - .gitconfig
  - .p10k.zsh
  - .tmux.conf
  - .zshrc.local
